fixtures:
  repositories:
    stdlib: git://github.com/puppetlabs/puppetlabs-stdlib.git
    augeasproviders:
      repo: git://github.com/hercules-team/augeasproviders.git
      ref: 'v1.0.1'
    create_resources: git://github.com/puppetlabs/puppetlabs-create_resources.git
  symlinks:
    sysctl: "#{source_dir}"
