name    'treydock-augeasproviders_sysctl'
version '0.0.1'
source 'git://github.com/treydock/puppet-augeasproviders_sysctl.git'
author 'treydock'
license 'Apache License, Version 2.0'
summary 'augeasproviders_sysctl module'
description 'augeasproviders_sysctl module'
project_page 'http://github.com/treydock/puppet-augeasproviders_sysctl'
dependency 'puppetlabs/stdlib', '>=3.2.0 <5.0.0'
dependency 'domcleal/augeasproviders', '>= 1.0.2'
