name    'treydock-sysctl'
version '0.0.1'
source 'git://github.com/treydock/puppet-sysctl.git'
author 'treydock'
license 'Apache License, Version 2.0'
summary 'sysctl module'
description 'sysctl module'
project_page 'http://github.com/treydock/puppet-sysctl'
dependency 'puppetlabs/stdlib', '>=3.2.0 <5.0.0'
dependency 'domcleal/augeasproviders, '>= 1.0.2'
